- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: ['docker.io', 'git', 'curl', 'python3-pip']
        state: present
        update_cache: yes

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      args:
        creates: /usr/local/bin/docker-compose


- hosts: user_service
  become: yes
  tasks:
    - name: Clone user repo
      git:
        repo: 'GIT_URL_USER_SERVICE'
        dest: /home/ubuntu/user-service
        update: yes
      become_user: ubuntu

    - name: Run user service
      shell: /usr/local/bin/docker-compose up -d --build
      args:
        chdir: /home/ubuntu/user-service


- hosts: order_service
  become: yes
  tasks:
    - name: Clone order repo
      git:
        repo: 'GIT_URL_ORDER_SERVICE'
        dest: /home/ubuntu/order-service
        update: yes
      become_user: ubuntu

    - name: Run order service
      shell: /usr/local/bin/docker-compose up -d --build
      args:
        chdir: /home/ubuntu/order-service


- hosts: monitoring
  become: yes
  tasks:
    - name: Clone monitoring repo
      git:
        repo: 'GIT_URL_MONITORING'  # contains prometheus.yml and docker-compose.yml
        dest: /home/ubuntu/monitoring
        update: yes
      become_user: ubuntu

    - name: Run monitoring stack
      shell: /usr/local/bin/docker-compose up -d --build
      args:
        chdir: /home/ubuntu/monitoring
